---
- name: Configure a Cisco IOS Switch
  hosts: all
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.ios
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: true
    myhostname: "c9800-1"
  tasks:
    - name: Configure top level configuration
      cisco.ios.ios_config:
        lines: hostname "{{ myhostname }}"

    - name: Remove the motd banner
      cisco.ios.ios_banner:
        banner: login
        state: absent

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified
