---
- name: Commit firewall candidate configuration
  hosts: all 
  connection: local

  vars:
    device:
      ip_address: "{{ inventory_hostname }}"
      username: "admin"
      password: "Changeme123"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Commit candidate configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ device }}"
      register: results
    - debug:
        msg: "Commit with Job ID: {{ results.jobid }} had output: {{ results.details }}"
