---
- name: Gather security rules
  hosts: all
  connection: local

  vars:
    device:
      ip_address: "{{ inventory_hostname }}"
      username: "admin"
      password: "Changeme123"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Get all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        gathered_filter: "*"
        state: gathered
      register: sec_rules

    - name: Output
      ansible.builtin.debug:
        msg: "{{ sec_rules }}"
